FROM bitnami/spark:3

USER root
RUN curl https://repo1.maven.org/maven2/com/amazonaws/aws-java-sdk-bundle/1.12.231/aws-java-sdk-bundle-1.12.231.jar --output /opt/bitnami/spark/jars/aws-java-sdk-bundle-1.12.231.jar
RUN curl https://repo1.maven.org/maven2/org/apache/hadoop/hadoop-aws/3.3.1/hadoop-aws-3.3.1.jar --output /opt/bitnami/spark/jars/hadoop-aws-3.3.1.jar
RUN curl https://repo1.maven.org/maven2/net/java/dev/jets3t/jets3t/0.9.4/jets3t-0.9.4.jar --output /opt/bitnami/spark/jars/jets3t-0.9.4.jar
RUN curl https://jdbc.postgresql.org/download/postgresql-42.3.5.jar --output /opt/bitnami/spark/jars/postgresql-42.3.5.jar

COPY ./workspace/postgres_to_s3.py /opt/bitnami/spark
COPY ./workspace/great_expectations_helper.py /opt/bitnami/spark

COPY ./requirements.txt /
RUN pip install -r /requirements.txt
