version: '2'

services:
  spark:
    container_name: master
    build:
      context: ./
      dockerfile: Dockerfile.Spark
    image: spark-air:latest
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - AWS_ACCESS_KEY=AKIATLEGUPNKMJLK7I7R
      - AWS_SECRET_KEY=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
      - AWS_S3_ENDPOINT=s3.amazonaws.com
      - AWS_BUCKET_NAME=d2b-internal-assessment-bucket-assessment
      
    ports:
      - '8090:8080'
  spark-worker:
    container_name: worker
    build:
      context: ./
      dockerfile: Dockerfile.Spark
    image: spark-air:latest
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - AWS_ACCESS_KEY=AKIATLEGUPNKMJLK7I7R
      - AWS_SECRET_KEY=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
      - AWS_S3_ENDPOINT=s3.amazonaws.com
      - AWS_BUCKET_NAME=new-wave-delta-lake

  db:
    image: postgres:14.2
    container_name: postgres
    restart: always
    # volumes:
    #     - ./database-data:/var/lib/postgresql/data/
    environment:
        POSTGRES_USER: root
        POSTGRES_PASSWORD: root
        POSTGRES_DB: dvdrental
    ports:
    - "5432:5432"
    
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    ports:
      - 3306:3306
    environment:
      USE_S3_STORAGE: 0
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_DATABASE: metastore_db