FROM bitnami/spark:3.2.1

USER root
RUN curl https://repo1.maven.org/maven2/com/amazonaws/aws-java-sdk-bundle/1.11.375/aws-java-sdk-bundle-1.11.375.jar --output /opt/bitnami/spark/jars/aws-java-sdk-bundle-1.11.375.jar
RUN curl https://repo1.maven.org/maven2/org/apache/hadoop/hadoop-aws/3.2.1/hadoop-aws-3.2.1.jar --output /opt/bitnami/spark/jars/hadoop-aws-3.2.1.jar
RUN curl https://repo1.maven.org/maven2/net/java/dev/jets3t/jets3t/0.9.4/jets3t-0.9.4.jar --output /opt/bitnami/spark/jars/jets3t-0.9.4.jar
RUN curl https://jdbc.postgresql.org/download/postgresql-42.3.5.jar --output /opt/bitnami/spark/jars/postgresql-42.3.5.jar
RUN curl https://repo1.maven.org/maven2/io/delta/delta-core_2.12/1.1.0/delta-core_2.12-1.1.0.jar --output /opt/bitnami/spark/jars/delta-core_2.12-1.1.0.jar


RUN curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
RUN apt-get update -y && apt-get upgrade -y
RUN apt-get install -y unzip
RUN unzip awscliv2.zip && rm awscliv2.zip
RUN ./aws/install -i /usr/local/aws-cli -b /usr/local/bin

COPY ./data_lakehouse/workspace/bronze_data_to_s3.py /opt/bitnami/spark
COPY ./data_lakehouse/workspace/silver_data.py /opt/bitnami/spark
COPY ./data_lakehouse/workspace/great_expectations_helper.py /opt/bitnami/spark

COPY ./data_lakehouse/requirements.txt /
RUN pip install -r /requirements.txt
